### ISSUE TITLE
Single letter album titles causing bug in Discord RPC

### ISSUE THREAD

**Issue by GOAT-Preacher** [twnlink/neptune-plugins#5]
While playing songs from the Album R by ROSÉ they wont show up in Discord and it shows as the last song keeps on getting played.
As other songs from her work as intended I suspected the sing letter name of the album to be at fault.
Behold: One google search for single letter album titles brings back L  by Steve Hillage and it also doesnt show up in Discord.

So the bug seems to only show up when the song is played from a single letter album.

**Comment by andregamma** [comment]
Discord Rich Presence requires that the text on the large image have at least 2 characters. An easy workaround would be not defining a text for the image at all if the album has less than 2 letters.
![image](https://github.com/twnlink/neptune-plugins/assets/31011359/3b759ee9-34a0-4b06-8bad-504eca43303b)

@twnlink what do you think?

**Comment by twnlink** [comment]
My suggestion here is to simply pad with spaces or any other invisible character if possible. I would work on this further but unfortunately I have been busy with IRL work.

**Comment by andregamma** [comment]
> My suggestion here is to simply pad with spaces or any other invisible character if possible. I would work on this further but unfortunately I have been busy with IRL work.

For some reason, I thought this would not work. But apparently it's fine. See #10 😊
