### ISSUE TITLE
Discord RPC stopped working. 

### ISSUE THREAD

**Issue by Elituz** [twnlink/neptune-plugins#6]
I reinstalled TIDAL, Discord, Neptune, and the plugin, none of which fixed the issue. I also restarted my computer multiple times. Just doesn't seem to work anymore. Though @purpl3F0x 's RPC still works. Just wondering why this one stopped working. Who knows.

**Comment by twnlink** [comment]
TIDAL changed the internal format that the tracklist is stored in. I've fixed it.

**Comment by Elituz** [comment]
> TIDAL changed the internal format that the tracklist is stored in. I've fixed it.

Thanks!
