### ISSUE TITLE
Any possibility for Listening to?

### ISSUE THREAD

**Issue by Elituz** [twnlink/neptune-plugins#7]
I've seen other unofficial applications say Listening to XXXX. Is this possible with this plugin? It would make seeing my activity more straightforward for my friends; thanks!

last.fm presence is a plugin for Discord/Vencord/BetterDiscord that I used to use that had that capability.

Vencord:https://github.com/Vendicated/Vencord/tree/main/src/plugins/lastfm
BetterDiscord:https://betterdiscord.app/plugin/LastFMRichPresence

**Comment by twnlink** [comment]
This would have to be implemented on the Discord side of things due to the "Listening to" type not being exposed as part of the RPC API.
